const ActionTypes = {
  GET_YOUTUBE_VIDEOS: 'GET_YOUTUBE_VIDEOS',
  GET_YOUTUBE_VIDEOS_SUCCESS: 'GET_YOUTUBE_VIDEOS_SUCCESS',
  GET_YOUTUBE_VIDEOS_FAIL: 'GET_YOUTUBE_VIDEOS_FAIL',
};
export default ActionTypes;
